"""Add read status to Comment model

Revision ID: cb80b07a4557
Revises: 2defbf238049
Create Date: 2025-10-17 18:21:59.105481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb80b07a4557'
down_revision = '2defbf238049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 修改后的代码
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_by_user', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('read_by_admin', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('read_by_admin')
        batch_op.drop_column('read_by_user')

    # ### end Alembic commands ###
