"""Add status column to Submission

Revision ID: f1c2c04d997c
Revises: 
Create Date: 2025-10-17 17:16:07.848607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c2c04d997c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        # 修改后的代码
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='待处理'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
